name: Canonical CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  get_changed_directories_list:
    name: Get List Of Changed Directories
    runs-on: ubuntu-latest
    outputs:
      connectors_list_json: ${{ steps.detect-changes.outputs.connectors_list_json }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history

      - name: Detect changed connectors
        id: detect-changes
        uses: ./.github/actions/detect-changes
        with:
          base_commit: ${{ github.event.pull_request.base.sha }}
          head_commit: ${{ github.event.pull_request.head.sha }}

  build_and_push:
    runs-on: ubuntu-latest
    if: needs.get_changed_directories_list.outputs.connectors_list_json != '[]'
    needs: [get_changed_directories_list]
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        dir: ${{ fromJson(needs.get_changed_directories_list.outputs.connectors_list_json) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history

      - name: Build and push image for ${{ matrix.dir }}
        uses: ./.github/actions/canonical-image-build-push
        with:
          connector: ${{ matrix.dir }}
          http-proxy: ${{ vars.HTTP_PROXY }}
          https-proxy: ${{ vars.HTTPS_PROXY }}
          dry-run: true
